### ISSUE TITLE
HTMLDocument.registerElement is deprecated.

### ISSUE THREAD

**Issue by DeadSue** [steelbrain/busy-signal#91]
Use `customElements.define` instead of `document.registerElement` see https://javascript.info/custom-elements
```
HTMLDocument.registerElement (file:///C:/Users/Andre/AppData/Local/atom-nightly/app-1.61.0-nightly12/resources/app.asar/static/index.js:160:12)
Object.<anonymous> (C:\Users\Andre\.atom\packages\busy-signal\lib\element.js:118:24)
Object.<anonymous> (C:\Users\Andre\.atom\packages\busy-signal\lib\element.js:124:3)
Module._compile (<embedded>:11:149913)
Object..js (<embedded>:11:153507)
Module.load (internal/modules/cjs/loader.js:992:32)
```

**Comment by nildoeti** [comment]
busy-signal (1 deprecation)
Use customElements.define instead of document.registerElement see https://javascript.info/custom-elements

HTMLDocument.registerElement - file:///usr/share/atom-beta/resources/app.asar/static/index.js:160:12
Object.<anonymous> - [/home/nildo/.atom/packages/busy-signal/lib/element.js:118:24](https://github.com/home/nildo/.atom/packages/busy-signal/lib/element.js:118:24)
Object.<anonymous> - [/home/nildo/.atom/packages/busy-signal/lib/element.js:124:3](https://github.com/home/nildo/.atom/packages/busy-signal/lib/element.js:124:3)
Module._compile - [<embedded>:11:149913](https://github.com/steelbrain/busy-signal/issues/%3Cembedded%3E:11:149913)
Object..js - [<embedded>:11:153507](https://github.com/steelbrain/busy-signal/issues/%3Cembedded%3E:11:153507)
Module.load - [internal/modules/cjs/loader.js:992:32](https://github.com/steelbrain/busy-signal/issues/internal/modules/cjs/loader.js:992:32)

**Comment by ntlspck** [comment]
same issue with Atom 1.61.0-beta0

**Comment by unbigote** [comment]
> same issue with Atom 1.61.0-beta0

yeah, me too

**Comment by JesseSteele** [comment]
> > same issue with Atom 1.61.0-beta0
> 
> yeah, me too

yeah, me three

**Comment by lineality** [comment]
[xxx@fedora env]$ atom-beta --version
Atom    : 1.61.0-beta0
Electron: 11.4.12
Chrome  : 87.0.4280.141
Node    : 12.18.3

message:
Deprecated calls
busy-signal (1 deprecation)
Use customElements.define instead of document.registerElement see https://javascript.info/custom-elements

HTMLDocument.registerElement - file:///usr/share/atom-beta/resources/app.asar/static/index.js:160:12
Object.<anonymous> - [/home/xxx/.atom/packages/busy-signal/lib/element.js:118:24](https://github.com/home/xxx/.atom/packages/busy-signal/lib/element.js:118:24)
Object.<anonymous> - [/home/xxx/.atom/packages/busy-signal/lib/element.js:124:3](https://github.com/home/xxx/.atom/packages/busy-signal/lib/element.js:124:3)
Module._compile - [<embedded>:11:149913](https://github.com/steelbrain/busy-signal/issues/%3Cembedded%3E:11:149913)
Object..js - [<embedded>:11:153507](https://github.com/steelbrain/busy-signal/issues/%3Cembedded%3E:11:153507)
Module.load - [internal/modules/cjs/loader.js:992:32](https://github.com/steelbrain/busy-signal/issues/internal/modules/cjs/loader.js:992:32)

**Comment by lineality** [comment]
busy-signal (1 deprecation)
Use customElements.define instead of document.registerElement see https://javascript.info/custom-elements

HTMLDocument.registerElement - file:///usr/share/atom-beta/resources/app.asar/static/index.js:160:12
Object.<anonymous> - [/home/oops/.atom/packages/busy-signal/lib/element.js:118:24](https://github.com/home/oops/.atom/packages/busy-signal/lib/element.js:118:24)
Object.<anonymous> - [/home/oops/.atom/packages/busy-signal/lib/element.js:124:3](https://github.com/home/oops/.atom/packages/busy-signal/lib/element.js:124:3)
Module._compile - [<embedded>:11:149913](https://github.com/steelbrain/busy-signal/issues/%3Cembedded%3E:11:149913)
Object..js - [<embedded>:11:153507](https://github.com/steelbrain/busy-signal/issues/%3Cembedded%3E:11:153507)
Module.load - [internal/modules/cjs/loader.js:992:32](https://github.com/steelbrain/busy-signal/issues/internal/modules/cjs/loader.js:992:32)

**Comment by nildoeti** [comment]
Devemos dizer adeus ao Atom. O GitHub anunciou o fim do aplicativo, que terminará em 15 de dezembro de 2022. Estou saindo do Atom  para o editor [Kate](https://kate-editor.org/pt-br/), pois o mesmo tem recursos suficientes para atender a demanda de um DEV.

**Comment by confused-Techie** [comment]
Just had a user report this issue as well when installing `busy-signal` from Pulsar.

Are any package maintainers aware if this package will continue to be updated now that Atom is sunset?

(Disclosure I am one of the lead devs on the Pulsar project) but updates to the package can be published to Pulsars Package Registry to get updates out if they'd like to

**Comment by steelbrain** [comment]
Hello! I have limited time for OSS lately and this is a fly-by comment but if someone from the community wants to address this, I can review the PR sometime soon.

**Comment by AlexWayfer** [comment]
> Hello! I have limited time for OSS lately and this is a fly-by comment but if someone from the community wants to address this, I can review the PR sometime soon.

It seems to be contributed in #95.

**Comment by nildoeti** [comment]
deprecated

**Comment by byte21516** [comment]
got the same deprecation

**Comment by ArthurZ** [comment]
The same occurs now in Pulsar:
![image](https://github.com/user-attachments/assets/069d0f62-64f1-4daa-934c-1824fe129059)

**Comment by saravg99** [comment]
> The same occurs now in Pulsar: ![image](https://private-user-images.githubusercontent.com/701808/362108695-069d0f62-64f1-4daa-934c-1824fe129059.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzNTM4MTcsIm5iZiI6MTcyNTM1MzUxNywicGF0aCI6Ii83MDE4MDgvMzYyMTA4Njk1LTA2OWQwZjYyLTY0ZjEtNGRhYS05MzRjLTE4MjRmZTEyOTA1OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwM1QwODUxNTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MjQ3ZTE1ZTBhMjU2ZDE1MWQxODA3ZDI3MTFkMmUxOTY3ZjNkMTE0YzE0ZDM1NDA3ZjM4Zjk0NGM2ZmM5NThiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.FABW5R3tVquU1V10Udvk0jvQkEBI2ByY3wmKooPdQL4)

I have the exact same issue

**Comment by DimDevOff** [comment]
> The same occurs now in Pulsar: ![image](https://github.com/user-attachments/assets/069d0f62-64f1-4daa-934c-1824fe129059)

I'm here for this reason too.
